version: '3'

networks:
  app:
    external:
      name: app

services:
  app:
    build:
      context: mattermost/app
      args:
        - edition=team
    restart: unless-stopped
    volumes:
      - ./persistent-data/mattermost/app/mattermost/config:/mattermost/config:rw
      - ./persistent-data/mattermost/app/mattermost/data:/mattermost/data:rw
      - ./persistent-data/mattermost/app/mattermost/logs:/mattermost/logs:rw
      - ./persistent-data/mattermost/app/mattermost/plugins:/mattermost/plugins:rw
      - ./persistent-data/mattermost/app/mattermost/client-plugins:/mattermost/client/plugins:rw
    environment:
      - MM_USERNAME=dbuser
      - MM_PASSWORD=dbpass
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://dbuser:dbpass@db:5432/mattermost?sslmode=disable&connect_timeout=10
    expose:
      - "8000"
    networks:
      - app

  web:
    build: mattermost/web
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - MATTERMOST_ENABLE_SSL=false
    ports:
      - "9200:80"
    networks:
      - app

